version: "3.2"
networks:
  blog-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.225.0/24

services:
  blog_backend:
    image: blog_backend:001
    container_name: blog_backend
    ports:
      - "8001:8001"
    command: sh start.sh web
    build:
      context: .
      dockerfile: ./Dockerfile
      command: sh start.sh web
    networks:
      - blog-network
    restart: always


