# Generated by Django 4.1.7 on 2023-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTimeOutLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('re_time', models.CharField(max_length=32, verbose_name='请求时间')),
                ('re_user', models.CharField(max_length=32, verbose_name='操作人')),
                ('re_ip', models.CharField(max_length=32, verbose_name='请求IP')),
                ('re_url', models.CharField(max_length=255, verbose_name='请求url')),
                ('re_method', models.CharField(max_length=11, verbose_name='请求方法')),
                ('re_content', models.TextField(null=True, verbose_name='请求参数')),
                ('rp_content', models.TextField(null=True, verbose_name='响应参数')),
                ('rp_code', models.TextField(null=True, verbose_name='响应码')),
                ('user_agent', models.TextField(null=True, verbose_name='请求浏览器')),
                ('access_time', models.IntegerField(verbose_name='响应耗时/ms')),
            ],
            options={
                'verbose_name': '平台超时操作日志表',
                'verbose_name_plural': '平台超时操作日志表',
                'db_table': 'ipam_access_timeout_logs',
            },
        ),
        migrations.CreateModel(
            name='OpLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('re_time', models.CharField(max_length=32, verbose_name='请求时间')),
                ('re_user', models.CharField(max_length=32, verbose_name='操作人')),
                ('re_ip', models.CharField(max_length=32, verbose_name='请求IP')),
                ('re_url', models.CharField(max_length=255, verbose_name='请求url')),
                ('re_method', models.CharField(max_length=11, verbose_name='请求方法')),
                ('re_content', models.TextField(null=True, verbose_name='请求参数')),
                ('rp_content', models.TextField(null=True, verbose_name='响应参数')),
                ('rp_code', models.TextField(null=True, verbose_name='响应码')),
                ('user_agent', models.TextField(null=True, verbose_name='请求浏览器')),
                ('access_time', models.IntegerField(verbose_name='响应耗时/ms')),
            ],
            options={
                'verbose_name': '平台操作日志表',
                'verbose_name_plural': '平台操作日志表',
                'db_table': 'ipam_op_logs',
            },
        ),
    ]
