# Generated by Django 4.1.7 on 2023-03-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=10000, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.CharField(blank=True, max_length=10000, verbose_name='关键词'),
        ),
    ]
